#!/bin/bash

set -e

# get directory of current scripts: https://stackoverflow.com/a/12694189/2103996
# convert to absolute path: https://stackoverflow.com/a/4045350/2103996
REPO_ROOT=$(cd ${BASH_SOURCE%/*} && pwd)
cd $REPO_ROOT

source "bin/common"

log_run "Installing TypeScript"
npm install > /dev/null

log_run "Cleaning"
git clean -fdxq -- lib

log_run "Compiling TypeScript source to JavaScript"
tsc

log_run "Bootstrapping meta package"
# hacks so that built JS can import from 'meta'
ln -fns ../lib/meta node_modules/meta
cat > lib/meta/package.json << EOF
{
  "name": "meta",
  "description": "configuration utilities",
  "version": "0.0.1",
  "main": "index.js",
  "private": true,
  "type": "module"
}
EOF

log_run "Running main"
node lib/meta/main.js
