#!/bin/bash

set -e

# get directory of current scripts: https://stackoverflow.com/a/12694189/2103996
# convert to absolute path: https://stackoverflow.com/a/4045350/2103996
REPO_ROOT=$(cd ${BASH_SOURCE%/*} && pwd)
cd $REPO_ROOT

source "bin/common"

# TODO: logging system that's better than echoing
echo "Installing TypeScript"
npm ci > /dev/null 2>&1

echo "Cleaning"
git clean -fdxq -- lib

echo "Compiling TypeScript source to JavaScript"
npx --no-install --quiet tsc

# hacks so that built JS can import from 'meta'
ln -fns ../lib/meta node_modules/meta
cat > lib/meta/package.json << EOF
{
  "name": "meta",
  "description": "configuration utilities",
  "version": "0.0.1",
  "main": "index.js",
  "private": true,
  "type": "module"
}
EOF

echo "Running main"
node lib/meta/main.js
