set  -g  jg_background                 2c2e34
set  -g  jg_foreground                 e2e2e3
set  -g  jg_black                      181819 
set  -g  jg_red                        fc5d7c 
set  -g  jg_green                      9ed072 
set  -g  jg_yellow                     e7c664 
set  -g  jg_blue                       76cce0 
set  -g  jg_magenta                    b39df3 
set  -g  jg_cyan                       f39660 
set  -g  jg_white                      e2e2e3 
set  -g  jg_br_black                   7f8490 
set  -g  jg_br_red                     fc5d7c 
set  -g  jg_br_green                   9ed072 
set  -g  jg_br_yellow                  e7c664 
set  -g  jg_br_blue                    76cce0 
set  -g  jg_br_magenta                 b39df3 
set  -g  jg_br_cyan                    f39660 
set  -g  jg_br_white                   e2e2e3 
set  -g  jg_orange                     d7827e
set  -g  jg_pink                       fab4d8
set  -g  jg_comment                    7f8490
set  -g  jg_selection                  d0d8d8

# Syntax Highlighting Colors
set  -g  fish_color_normal             $jg_foreground
set  -g  fish_color_command            $jg_cyan
set  -g  fish_color_keyword            $jg_pink
set  -g  fish_color_quote              $jg_yellow
set  -g  fish_color_redirection        $jg_foreground
set  -g  fish_color_end                $jg_orange
set  -g  fish_color_error              $jg_red
set  -g  fish_color_param              $jg_magenta
set  -g  fish_color_comment            $jg_comment
set  -g  fish_color_selection          --background=$jg_selection
set  -g  fish_color_search_match       --background=$jg_selection
set  -g  fish_color_operator           $jg_green
set  -g  fish_color_escape             $jg_pink

# Completion Pager Colors
set  -g  fish_color_autosuggestion     $jg_comment
set  -g  fish_pager_color_progress     $jg_comment
set  -g  fish_pager_color_prefix       $jg_cyan
set  -g  fish_pager_color_completion   $jg_foreground
set  -g  fish_pager_color_description  $jg_comment
