set  -g  jg_background                 faf4ed
set  -g  jg_foreground                 575279
set  -g  jg_black                      575279
set  -g  jg_red                        b4637a
set  -g  jg_green                      618774
set  -g  jg_yellow                     ea9d34
set  -g  jg_blue                       286983
set  -g  jg_magenta                    907aa9
set  -g  jg_cyan                       56949f
set  -g  jg_white                      e5e9f0
set  -g  jg_br_black                   5f5695
set  -g  jg_br_red                     c26d85
set  -g  jg_br_green                   629f81
set  -g  jg_br_yellow                  eea846
set  -g  jg_br_blue                    2d81a3
set  -g  jg_br_magenta                 9a80b9
set  -g  jg_br_cyan                    5ca7b4
set  -g  jg_br_white                   e6ebf3
set  -g  jg_orange                     d7827e
set  -g  jg_pink                       d685af
set  -g  jg_comment                    9893a5
set  -g  jg_selection                  d0d8d8

# Syntax Highlighting Colors
set  -g  fish_color_normal             $jg_foreground
set  -g  fish_color_command            $jg_cyan
set  -g  fish_color_keyword            $jg_pink
set  -g  fish_color_quote              $jg_yellow
set  -g  fish_color_redirection        $jg_foreground
set  -g  fish_color_end                $jg_orange
set  -g  fish_color_error              $jg_red
set  -g  fish_color_param              $jg_magenta
set  -g  fish_color_comment            $jg_comment
set  -g  fish_color_selection          --background=$jg_selection
set  -g  fish_color_search_match       --background=$jg_selection
set  -g  fish_color_operator           $jg_green
set  -g  fish_color_escape             $jg_pink

# Completion Pager Colors
set  -g  fish_color_autosuggestion     $jg_comment
set  -g  fish_pager_color_progress     $jg_comment
set  -g  fish_pager_color_prefix       $jg_cyan
set  -g  fish_pager_color_completion   $jg_foreground
set  -g  fish_pager_color_description  $jg_comment
