set   material_white       EEFFFF
set   material_gray        717CB4
set   material_black       000000
set   material_red         F07178
set   material_green       C3E88D
set   material_yellow      FFCB6B
set   material_blue        82AAFF
set   material_paleblue    B0C9FF
set   material_cyan        89DDFF
set   material_purple      C792EA
set   material_orange      F78C6C
set   material_pink        FF9CAC
set   material_darkred     DC6068
set   material_darkgreen   ABCF76
set   material_darkyellow  E6B455
set   material_darkblue    6E98EB
set   material_darkcyan    71C6E7
set   material_darkpurple  B480D6
set   material_error       FF5370
