set  -g  material_white       EEFFFF
set  -g  material_gray        717CB4
set  -g  material_black       000000
set  -g  material_red         F07178
set  -g  material_green       C3E88D
set  -g  material_yellow      FFCB6B
set  -g  material_blue        82AAFF
set  -g  material_paleblue    B0C9FF
set  -g  material_cyan        89DDFF
set  -g  material_purple      C792EA
set  -g  material_orange      F78C6C
set  -g  material_pink        FF9CAC
set  -g  material_darkred     DC6068
set  -g  material_darkgreen   ABCF76
set  -g  material_darkyellow  E6B455
set  -g  material_darkblue    6E98EB
set  -g  material_darkcyan    71C6E7
set  -g  material_darkpurple  B480D6
set  -g  material_error       FF5370

set  -g  fish_color_error        $material_error
set  -g  fish_color_command      $material_darkblue
set  -g  fish_color_operator     $material_darkcyan
set  -g  fish_color_param        $material_blue
set  -g  fish_color_quote        $material_darkgreen
set  -g  fish_color_end          $material_darkpurple
set  -g  fish_color_cwd          $material_cyan
set  -g  fish_color_escape       $material_orange
set  -g  fish_color_normal       $material_white
set  -g  fish_color_redirection  $material_paleblue
